[build]
  command = "npm run build"
  publish = "dist"

# Редирект для SPA (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Кэширование статических файлов
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
